### ISSUE TITLE
联想mdm建议直接hook systemserver

### ISSUE THREAD

**Issue by ljlVink** [HexoCustomPass/Myipad-Hook#2]
com.android.server.mia.MiaMdmPolicyService

根治）

**Comment by Twinkle-Wong** [comment]
如果你会 直接pr就好 或者 fork

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: ljlVink ***@***.***>
Sent: Sunday, May 29, 2022 4:41:17 PM
To: HexoCustomPass/Myipad-Hook ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HexoCustomPass/Myipad-Hook] 联想mdm建议直接hook systemserver (Issue #2)


com.android.server.mia.MiaMdmPolicyService

根治）

―

**Comment by ljlVink** [comment]
算了（ 太麻烦了好几百个函数同时钩似乎没啥意义
